### ISSUE TITLE
Possible deadlock when receiving nack?

### ISSUE THREAD

**Issue by btrask** [cocagne/multi-paxos-example#4]
Hi! First let me say thank you for this fantastic project. It's been immensely helpful for me learning how Paxos works.

I'm also still far from an expert here, and I haven't actually tried reproducing this bug. It's purely theoretical and I might be wrong.

In [receive_nack](https://github.com/cocagne/multi-paxos-example/blob/1f23daaa5e096b7e3c1402125ef7ff98bd1aee18/composable_paxos.py#L192), the proposer waits until it receives a quorum of nacks before retrying with `prepare()`. In a scenario where at least one peer is partitioned, it's possible for the responses to be split between successful promises and nacks such that a quorum of neither ever happens. In that case, the algorithm can get stuck, even though an overall quorum of peers is responding.

Concrete example: 5 nodes total (ABCDE). 3 are up (ABC) and 2 are offline (DE). A sends a prepare message to BC. B accepts the prepare and responds with a promise. C has already seen a higher prepare (perhaps from D before it went offline) and nacks. Now A has agreement from B and disagreement from C, and is stuck waiting for another vote from D or E in order to reach a three node (including itself) quorum.

There are a couple of potential ways this could be resolved. The simplest would be to send a new prepare as soon as we receive the _first_ nack, although that could be inefficient.

Am I missing something or is this a real problem?

Thanks,
Ben

**Comment by cocagne** [comment]
Thanks Ben. You definitely spotted a potential problem with that
implementation and the deadlock scenario you describe can certainly happen.
This area is one of the trouble spots for practical Paxos implementations
and it gets harder and harder to effectively deal with as you ramp up your
performance requirements. For example, a simple mechanism you could use to
resolve the deadlock would be to simply retransmit the original proposal
every now and again or to abandon the current proposal after a while,
increment the proposal counter, and try again from the beginning. Those all
involve delays and timeouts though so they drive up latency. This is one of
the areas the core algorithm leaves unspecified and you're on your own to
come up with a solution that matches the requirements of your application.

Tom

**Comment by btrask** [comment]
I see.

Thanks for the info and great work!
