### ISSUE TITLE
Question about advancing the paxos instance

### ISSUE THREAD

**Issue by jivimberg** [cocagne/multi-paxos-example#5]
When advancing the paxos instance:

https://github.com/cocagne/multi-paxos-example/blob/924ae6c8690225d83718a26c6932c7c3c3ba493a/replicated_value.py#L190

Seems like like you're setting the value for the next instance instead of the current one. 

I understand that the instance number needs to be advanced, but I'd have expected to happen only after saving the current consented value for the current instance. But looking into the `self.advance_instance` implementation that doesn't seem to be what's happening.

ps: Thanks for putting this repo together, it's been a great help!

**Comment by cocagne** [comment]
It's easy to get confused with these things. Your description of what's
happening isn't wrong but I think your perspective is a little off. Think
of it this way, at any given point in time there is only one consensual
value and we use Paxos to change that value. Each time consensus on a new
value is reached, we save it to disk to ensure we don't loose it and
advance to the next instance of paxos for choosing the next consensual
value. So we don't save a value for the "next" instance, only the
most-recently-completed one. The "next" instance could remain outstanding
for days and the process for choosing a new value doesn't begin until some
outside entity (like the cli) sends a value to consider.

Does that help?

Tom

**Comment by jivimberg** [comment]
Ohh! I see... that makes sense!
I guess what confused me is the check that's done when receiving messages
https://github.com/cocagne/multi-paxos-example/blob/924ae6c8690225d83718a26c6932c7c3c3ba493a/replicated_value.py#L130-L133

I took that to mean: _"only process messages for the instance number we're currently trying to agree upon"_. And I guess it serves that purpose only that when they reach a resolution it's going to be stored in instance_number + 1. Right?

**Comment by cocagne** [comment]
Mostly. It means "ignore all messages that aren't messages for the current
Paxos instance". Both past and future messages must be taken into
consideration. It could well be that the network delayed delivery of a
message by a few seconds during which time we could have transitioned to
the new Paxos instance. So the instance number for that packet would be
less than the current value. It's also possible that we lost connection to
the peers for a while and they agreed upon the resolution of the paxos
instance a while ago and are now on the next one.... or 100+ instances
further down the chain. In that case, we'll need to catch up to the current
instance before we can participate again in the resolution process. That
catch-up process though is outside the scope of that class. All that class
needs to do is ensure it constrains all of its message handling to that
single Paxos instance.

**Comment by jivimberg** [comment]
Super clear. Thanks for the help!
