### ISSUE TITLE
Question about sync_strategy

### ISSUE THREAD

**Issue by jivimberg** [cocagne/multi-paxos-example#6]
As far as I can tell the sync_strategy seems to synchronize the node with the current state of the multi-paxos chain, but doesn't get up to date about previous resolved values  on the chain, right?

**Comment by cocagne** [comment]
Correct, it doesn't attempt to hold on to any historical values.

**Comment by jivimberg** [comment]
Oh ok, I thought I was missing something...
Thanks for the prompt response!
